### PR TITLE
update gh account and repo

### PR DESCRIPTION
**Pull request by isSerge**
This is a forked repo of https://github.com/KilleenCode/tauri-update-cloudflare, required for deployment of Tauri update server as Cloudflare edge function

### CODE REVIEW

**Review by nazar-pc — APPROVED** [review]
I wish we didn't have to maintain fork for this, but looks like readme suggests it. No description though of what it actually does and how.

**Comment by isSerge** [comment]
@nazar-pc this is a temporary setup for our update server, we discussed with @ch00mba that it would be nice to use Terraform in the long run

**Comment by nazar-pc** [comment]
But terraform is just for infra, it doesn't do anything with files updater would use to actually update and such

**Comment by isSerge** [comment]
@nazar-pc we would still need an update server. It's just a matter of how and where we deploy it, this seems like an easy solution for now

**Comment by nazar-pc** [comment]
I'm not against it, just hoped desktop app can just reach out to CDN where we'll upload executables as part of release process or something.

**Review by ghost — APPROVED** [review]
Let’s try it

**Pull request merged**
